export const symbolsWithBrl =
  '["BTCBRL","USDTBRL","ETHBRL","BNBBRL","BUSDBRL","XRPBRL","LINKBRL","LTCBRL","DOGEBRL","ADABRL","DOTBRL","CHZBRL","ENJBRL","BTTBRL","WINBRL","HOTBRL","ETCBRL","MATICBRL","SHIBBRL","SOLBRL","CAKEBRL","AAVEBRL","AXSBRL","FISBRL","C98BRL","AVAXBRL","FTMBRL","MANABRL","SANTOSBRL","GALABRL","SANDBRL","LUNABRL","ATOMBRL","GMTBRL","APEBRL","GALBRL"]';
